apiVersion: v1
kind: ConfigMap
metadata:
  name: geotools-config
data:
  PORT: "3000"
  STORAGE_MODE: "auto"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geotools-cities-data
binaryData:
  big_cities.json: ${BASE64_ENCODED_CITIES_DATA}  # This needs to be replaced with actual base64 encoded data
