apiVersion: v1
kind: Service
metadata:
  name: geotools-api
  labels:
    app: geotools-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: geotools-api
