apiVersion: v1
kind: Secret
metadata:
  name: geotools-secrets
type: Opaque
data:
  REDIS_PASSWORD: ""  # Base64 encoded empty string for now
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geotools-sqlite-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
